apiVersion: apps/v1
kind: Deployment
metadata:
  name: epgstation-nginx
spec:
  template:
    spec:
      containers:
        - name: nginx
          resources:
            limits:
              cpu: 0.5
              memory: 200Mi
              ephemeral-storage: 32M
            requests:
              cpu: 0.1
              memory: 150Mi
              ephemeral-storage: 32M
      volumes:
        - name: nginx-cache
          emptyDir:
            medium: Memory
            sizeLimit: 128Mi
        - name: nginx-pid
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
