apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster.yaml

helmcharts:
  - name: rook-ceph
    repo: https://charts.rook.io/release
    version: v1.16.5
    releaseName: rook-ceph
    valuesFile: ./values.yaml
