version: 2
updates:
  - package-ecosystem: "docker"
    directories:
      - "/Dockerfile/*"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
