---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-token
spec:
  encryptedData:
    TUNNEL_TOKEN: AgC3KkrOEF80+XMXDXKEGE3GY10NF5fTvKh/ArqgjbZZzCDGepKO8XILrBokSmRvvmqZ8nanwjEVuSDMClb3L/eUWjXVuOUrA9TovUcaHECY9BMtRieYl3afSY1bHWBC+p2hvWqxNegsaNDSBvL853fBSlHA0PS47D2Vm9X3H1b8UAsQmWLejsiMgaR/Ok30QXEs4LniQ37fFoyxQHaBCMru3mKmhUHhapswo6Onq+cwtz8MohtIue4LRPD3d+uosBdcbYYm/AssCEN8AvKdj8JZRq3VsDuhXjoINoer55Ao8PmQ3FWLqEFcGj/dHj0rgVDpR8aSmYTmb+YLTrYREfUBwx+G/sferBl4ds1USLsvelzxN92EJY9roIg3feJ6GaAJWCMoaM/Pp4n8chUy+EOsPz63D2AWqX86Wmfc5mYX5eoYwSj/al2IxoJBdSxdjr8olxbmZJxyCVl5XvG/cw3mME0TW8kHguaJ8t53735hHbLUvDq/l3Pi5X8a2esFkMD2gJ5IF2BBMLA3SiuS3VvmFeuyu14XYnjxVMSfuFQj+2JWdTe1UPtdmgIJpjP0vw338HNhB0wWbfEHdJp2q0Do0pIuDqtzz+xXOmslS0Kq6xilOQ/sKO9071pZ50B/NKaq71JNhjL5o29gSyxxthKuLRPx5Sub1JjjhjoZwxX4E4yi8TRPTninFmOPO+5j5xjkDwy/NOSWX5uyOVa0VzSRIzmEqtKkp3lTPnOrGfR3z/sFVvuU6keX49XqJFqmGh5ZfgCW6aXxeMxAMCnmbjdqSBlQ+pZi5m3K12t2YVmC/7y71rzN4NFOKSIQQaq6NBHWlrHmCUdUCOD0AWUxOe7iiYQ7DSfUpyh/tmNMXaSGfojmHWbPUAh8tnuz+4I9kyPUWvAamEYnEMNl0BwGCb6Ic3DQicI8TCgcNBiT0s9YsISd7N70AJuM
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-token
    type: Opaque
