apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmcharts:
  - name: harbor
    repo: https://helm.goharbor.io
    version: v1.17.1
    releaseName: harbor
    valuesInline:
      expose:
        type: clusterIP
        tls:
          enabled: false
      persistence:
        persistentVolumeClaim:
          redis:
            storageClass: rook-ceph-block
          trivy:
            storageClass: rook-ceph-block
          registry:
            storageClass: rook-ceph-block
          database:
            storageClass: rook-ceph-block
          jobservice:
            jobLog:
              storageClass: rook-ceph-block
