apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmcharts:
  - name: gha-runner-scale-set
    repo: oci://ghcr.io/actions/actions-runner-controller-charts
    version: 0.11.0
    releaseName: gha-runner-scale-set
    valuesInline:
      githubConfigUrl: https://github.com/fetburner/homelab-infra
      githubConfigSecret:
        github_token: dummy
      controllerServiceAccount:
        name: arc-systems-gha-rs-controller
        namespace: arc-systems
