---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gha-runner-scale-set-gha-rs-github-secret
spec:
  encryptedData:
    github_token: AgAcjGaSRsIKhNGmKRGiNqbsLqtxgZpNfq5PrOrD/aishJuvPxC7yX4WnxE7uFmTWZVEkWV+jrRUqJNMrwozumLC7foNyEQy9ts+27nN56Nbp3ZlX1PJ144v0jfhzCsY9GonGWYYtqFb/o/7RiNEQQouiS8JaEgOixZCJMoYVRH+tMautakT0zW7Lxa8toEmZS5xsXSGyus+NKDbtlg4RnQFdYGUzequkataU5SNX5BZZJyM5WDrT/HP7DuauarYbyZ+ItfmviWCsOI8xmD/ByIqQpyzxkfNpeCVPIRdqCT0ipZYrQAyG51/I+5eP4+Pyx1IorcTHONH+WhrrAWLaWjAA/S/SjhQE5GpOmPYZP3x9U4ySih8ARm2PhfgDTL/FYut5DLmiXalYcXzQtyh8vNOFjYT5XdeoxfNTccilzClG2XLkxBLFNWVN+h+Rgr6hiREBU9DoUzjsKjQAkPt01PpTJ5rcvCFxq3RXMiBWxAUldIiJVERgVdplewMdRnJMpmmA0XMg2vy13wY2krVcohdqstZWev5XsdOidVIdmxiEGDzKLLaJ7j3SLAKjGT2o7d8XfPlUy4KOEqiYK2cU00Ju/SUrc/mEXNHWxZJEWIb/0X1EMXXuqz9cdX4XIFCyFvI8/eJaCb1kC5eCJ0vYPPhrvoujEIkIzakckolf3NgQmQWltv/I473ao1Ij6FZSKmIx8oBq1bsHF0QZCwRBGpifbQElqRQ2ZOLdxKcNORIJsm7GlJ/5sDH
  template:
    metadata:
      creationTimestamp: null
      name: gha-runner-scale-set-gha-rs-github-secret
    type: Opaque
