apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmcharts:
  - name: rancher
    repo: https://releases.rancher.com/server-charts/stable
    version: v2.11.3
    releaseName: rancher
    kubeVersion: 1.32.5
    valuesInline:
      ingress:
        enabled: false
