apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rokuban

resources:
  - ../base

patches:
  - path: deployment.patch.yaml

images:
  # Dockerfile/rokuban-full を追加した commit の multi-arch image。
  - name: ghcr.io/fetburner/rokuban-full
    newTag: bb87ceaa24a9267690e081e5711991afaca43b32
