apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    path: kubernetes/argocd
    repoURL: https://github.com/fetburner/homelab-infra
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  project: default
  source:
    path: kubernetes/grafana
    repoURL: https://github.com/fetburner/homelab-infra
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-mirakc-epgstation
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: epgstation
  project: default
  source:
    path: kubernetes/k8s-mirakc-epgstation
    repoURL: https://github.com/fetburner/homelab-infra
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph
  project: default
  source:
    path: kubernetes/rook-ceph
    repoURL: https://github.com/fetburner/homelab-infra
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: descheduler
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/descheduler
    chart: descheduler
    targetRevision: 0.32.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: default
  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    chart: sealed-secrets
    targetRevision: 2.17.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-systems
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-systems
  project: default
  source:
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    chart: gha-runner-scale-set-controller
    targetRevision: 0.10.1
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: apiextensions.k8s.io
      name: autoscalinglisteners.actions.github.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextensions.k8s.io
      name: autoscalingrunnersets.actions.github.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextensions.k8s.io
      name: ephemeralrunners.actions.github.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
    - group: apiextensions.k8s.io
      name: ephemeralrunnersets.actions.github.com
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runner
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-runner
  project: default
  source:
    path: kubernetes/arc-runner
    repoURL: https://github.com/fetburner/homelab-infra
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
