apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: cloudflared
    app.kubernetes.io/name: argocd-cloudflared
    app.kubernetes.io/part-of: argocd
  name: argocd-cloudflared
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-cloudflared
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared
          args:
            - tunnel
            - run
          envFrom:
            - secretRef:
                name: tunnel-token
