apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ../base
  - sealedsecret.yaml
  - deployment.yaml
  - application.yaml

patches:
  - path: secret.patch.yaml
  - path: configmap.patch.yaml
