apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app.kubernetes.io/component: mysqldump
    app.kubernetes.io/name: mysqldump
    app.kubernetes.io/part-of: grafana
  name: mysqldump
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: mysqldump
        spec:
          securityContext:
            runAsUser: 10001
            runAsGroup: 10001
          containers:
            - name: mysqldump
              image: mysql:8.4
              command: ["/bin/sh"]
              args: ["-c", "/usr/bin/mysqldump -u${MYSQL_USER} -p${MYSQL_PASSWORD} -h${MYSQL_HOST} ${MYSQL_DATABASE} > /backup/`date +%Y%m%d`-grafana.sql"]
              envFrom:
                - secretRef:
                    name: tidb-serverless
              volumeMounts:
                - name: mysqldump
                  mountPath: /backup
              securityContext:
                readOnlyRootFilesystem: true
          restartPolicy: Never
          volumes:
            - name: mysqldump
              persistentVolumeClaim:
                claimName: mysqldump
