apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - clusterrolebinding.yaml
  - clusterrole.yaml
  - cronjob.yaml
  - daemonset.yaml
  - deployment.yaml
  - serviceaccount.yaml
  - service.yaml
  - statefulset.yaml
  - networkpolicy.yaml
