apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: cloudflared
    app.kubernetes.io/name: cloudflared
    app.kubernetes.io/part-of: cloudflared
  name: cloudflared
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: cloudflared
      app.kubernetes.io/name: cloudflared
      app.kubernetes.io/part-of: cloudflared
  template:
    metadata:
      labels:
        app.kubernetes.io/component: cloudflared
        app.kubernetes.io/name: cloudflared
        app.kubernetes.io/part-of: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared
          args:
            - tunnel
            - run
          envFrom:
            - secretRef:
                name: tunnel-token
          securityContext:
            readOnlyRootFilesystem: true
