apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-sidecar
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: thanos-sidecar
          envFrom:
            - configMapRef:
                name: thanos-bucket
            - secretRef:
                name: thanos-bucket
          resources:
            limits:
              cpu: 0.5
              memory: 100Mi
              ephemeral-storage: 200M
            requests:
              cpu: 0.1
              memory: 50Mi
              ephemeral-storage: 200M
        - name: prometheus
          resources:
            limits:
              cpu: 0.5
              memory: 1Gi
              ephemeral-storage: 200M
            requests:
              cpu: 0.1
              memory: 500Mi
              ephemeral-storage: 200M
      securityContext:
        runAsUser: 0
        runAsGroup: 0
  volumeClaimTemplates:
    - metadata:
        labels:
          app.kubernetes.io/name: prometheus
          app.kubernetes.io/part-of: grafana
        name: prometheus
      spec:
        storageClassName: rook-ceph-block
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 4Gi
