apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns-all
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rokuban-allow
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: rokuban
      app.kubernetes.io/component: monolith
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: cloudflared
          podSelector:
            matchLabels:
              pod: cloudflared
      ports:
        - protocol: TCP
          port: 40773
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: grafana
          podSelector:
            matchLabels:
              app.kubernetes.io/name: thanos-sidecar
      ports:
        - protocol: TCP
          port: 40773
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: epgstation
          podSelector:
            matchLabels:
              app.kubernetes.io/name: epgstation-mirakc
      ports:
        - protocol: TCP
          port: 40772
    - ports:
        - protocol: TCP
          port: 5432
