apiVersion: v1
kind: Service
metadata:
  name: rokuban-api
  labels:
    app.kubernetes.io/name: rokuban
    app.kubernetes.io/component: monolith
    app.kubernetes.io/part-of: rokuban
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rokuban
    app.kubernetes.io/component: monolith
  ports:
    - name: http
      port: 40773
      targetPort: http
      protocol: TCP
