apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rook-ceph

resources:
  - ../base
  - namespace.yaml
  - storageclass.yaml
  - cephblockpool.yaml
  - cephobjectstore.yaml

patches:
  - path: cluster.patch.yaml
