apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: harbor
    component: cloudflared
    app.kubernetes.io/component: cloudflared
    app.kubernetes.io/name: cloudflared
    app.kubernetes.io/part-of: harbor
  name: harbor-cloudflared
spec:
  selector:
    matchLabels:
      app: harbor
      component: cloudflared
  template:
    metadata:
      labels:
        app: harbor
        component: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared
          args:
            - "tunnel"
            - "run"
          envFrom:
            - secretRef:
                name: tunnel-token
          securityContext:
            readOnlyRootFilesystem: true
