apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: harbor

resources:
  - ../base
  - deployment.yaml

patches:
  - path: deployment.patch.yaml
  - path: statefulset.patch.yaml
