apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: harbor-database
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: harbor-redis
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: harbor-trivy
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
