name: Terraform Plan

on:
  pull_request:
    paths:
      - 'terraform/**'
      - 'tfaction-root.yaml'
      - 'aqua.yaml'
      - '.github/workflows/terraform-plan.yaml'

permissions:
  contents: write
  pull-requests: write

jobs:
  list-targets:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.list.outputs.targets }}
    steps:
      - uses: actions/checkout@v7

      - uses: suzuki-shunsuke/tfaction@latest
        id: list
        with:
          action: list-targets
          github_token: ${{ github.token }}

  plan:
    name: "plan (${{ matrix.target.target }})"
    runs-on: ${{ matrix.target.runs_on }}
    needs: [list-targets]
    if: join(fromJSON(needs.list-targets.outputs.targets), '') != ''
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJSON(needs.list-targets.outputs.targets) }}
    env:
      TFACTION_TARGET: ${{ matrix.target.target }}
      TFACTION_WORKING_DIR: ${{ matrix.target.working_directory }}
      TFACTION_JOB_TYPE: ${{ matrix.target.job_type }}
      TFACTION_SKIP_TERRAFORM: ${{ matrix.target.skip_terraform }}
    steps:
      - uses: actions/checkout@v7

      - uses: suzuki-shunsuke/tfaction@latest
        id: setup
        with:
          action: setup
          github_token: ${{ github.token }}

      - uses: suzuki-shunsuke/tfaction@latest
        with:
          action: terraform-init
          github_token: ${{ github.token }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}

      - uses: suzuki-shunsuke/tfaction@latest
        with:
          action: plan
          github_token: ${{ github.token }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          RANCHER_URL: ${{ vars.RANCHER_URL }}
          RANCHER_TOKEN_KEY: ${{ secrets.RANCHER_TOKEN_KEY }}
